### ISSUE TITLE
Accent color changed listener

### ISSUE THREAD

**Issue by ricardoboss** [bdlukaa/system_theme#25] opened 2023-07-05 17:31 UTC
Hi, great project!

Is it possible to provide a callback that gets invoked whenever the accent color on the given system changes?

Currently, I (or the user) have to restart the app for it to pick up the new accent color.

**Comment by bdlukaa** [comment] 2023-07-07 14:21
Duplicate of #6

**Closed as not planned by bdlukaa** 2023-07-07 14:21 UTC
Labels: duplicate

**Comment by ricardoboss** [comment] 2023-07-07 14:33
I don't think #6 is a dupe since it only focusses on Windows and is more of an RFC on the linked PR, not an issue. Also: the other issue doesn't answer my question, it only hints at the possibility that something like this is possible on Windows.

**Comment by bdlukaa** [comment] 2023-07-07 21:48
I am afraid Windows and Linux are the only platforms that have a listener to window changes.

The linked PR was updated and now has a working example and a showcase. I will merge #7 but keep #6 open for further investigation on a listener to accent colors on the other platforms!
